---
title: "TB in silico mixture dataset"
output: 'github_document'
---


```{r setup}
library(SeqArray)
library(tidyverse)
library(magrittr)
```

```{r download_ref}
ref_url <- 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/195/955/GCA_000195955.2_ASM19595v2/GCA_000195955.2_ASM19595v2_genomic.fna.gz'
ref_fn <- file.path('1.work', basename(ref_url))
if (!file.exists(ref_fn)) { download.file(ref_url, ref_fn) }
```

```{r create_downloader_script, eval=FALSE}
ids <- read_rds('1.work/nejmoa1800474_subset_metadata.rds')$sample_id
PARALLEL = 8
str_c(
  '#!/usr/bin/env bash',
  '# requires sra-toolkit fasterq-dump',
  str_c('echo "', str_c(ids, collapse = ' '), '" |'),
  '\ttr \' \' \'\\n\' |',
  str_c('\txargs -n1 -P', PARALLEL, ' -i bash -c "fasterq-dump -3 {} && gzip {}_1.fastq && gzip {}_2.fastq"'),
  sep = '\n') %>% 
  write_lines('0.fasterq_dump.sh')
```

```{r input_samples}
# run 0.fasteq_dump.sh to download all fastqs first
# set to directory of FASTQs from SRA-tools fastq-dump on your system
input_fastq_dir <- './fastq'

# 950 random samples from DOI:10.1056/NEJMoa1800474 with:
  # platform == Illumina HiSeq 2500
  # median_depth >= 100
  # fastp_pct_pass >= 95
  # pct_mapped >= 95
  # read lengths >= 290

samples_input <- 
  read_rds('1.work/nejmoa1800474_subset_metadata.rds') %>% 
  mutate(
    fastq1 = file.path(normalizePath(input_fastq_dir), str_c(sample_id, '_1.fastq.gz')),
    fastq2 = file.path(normalizePath(input_fastq_dir), str_c(sample_id, '_2.fastq.gz'))
  )
```


* downsample all to 100X
* run though all methods
```{r downsample_and_predict, eval=FALSE}
if (!dir.exists('1.work/downsample')) {
  dir.create('1.work/downsample')
}
# create manifest for downsampling
samples_input %>% 
  transmute(id = str_c(sample_id, '_100X'),
            sample = sample_id,
            frac = 100 / median_depth,
            seed = 1,
            fq1 = fastq1,
            fq2 = fastq2) %>% 
  write_tsv('1.work/downsample/manifest.tsv')
## cd '1.work/downsample/manifest.tsv' and run nextflow ./TBpipeR/workflows/benchmarking/FastqMixer/main.nf'

# create directory to run through all tools in  TBpipeR benchmark
if (!dir.exists('1.work/100X_pred')) {
  dir.create('1.work/100X_pred')
}
# copy nextflow config
file.copy('nextflow.config', '1.work/100X_pred/')
# copy ref
file.copy(ref_fn, '1.work/100X_pred/')
# create manifest
read_tsv('1.work/downsample/output/output_manifest.tsv') %>% 
  rename(sample = id) %>% 
  mutate(sample = str_remove(sample, '_100X')) %>% 
  write_tsv('1.work/100X_pred/manifest.tsv2')
# run through TBpipeR Benchmark suite - nextflow run ./TBpipeR/main.nf

# save results as RDS
read_tsv('1.work/100X_pred/output/combined_results.tsv') %>% 
  saveRDS('1.work/100X_combined_results.rds')

```

```{r predictions_at_100X}
# read_rds('1.work/100X_combined_results.rds') %>%  View()
pred_100X <- 
  read_rds('1.work/100X_combined_results.rds') %>% 
  group_by(method, sample) %>% 
  summarise(n_mix = n(), 
            minor_prop = 1 - max(proportion, na.rm = T),
            .groups = 'drop')

pred_100X_smry <-
  pred_100X %>% 
  group_by(sample) %>% 
  summarise(n_pred_mix = sum(n_mix > 1),
            mean_n_mix = mean(n_mix),
            mean_prop = mean(minor_prop))
```


```{r sample_BAF}
# from TBpipeR::VCF_TO_GDS
# gds <- seqOpen('in_silico_data/in_silico_bench.concat.gds', allow.duplicate = T)
# af <- map(0:3, ~seqAlleleFreq(gds, ref.allele = .)) %>% do.call(cbind, .)
# # remove sites with no alt alleles
# include <- af[,1] < 1
# SeqArray::seqSetFilter(gds, variant.sel =include)
# # determine which alt allele is most common
# alt <- map_int(seq_len(nrow(af)), \(x) which.max(af[x,-1]))[include] + 1
# 
# AD0 <- seqGetData(gds, 'annotation/format/AD')$data
# AD <- array(integer(), dim = c(nrow(AD0), ncol(AD0)/4, 4))
# for (i in seq(4)) {
#   AD[, , i] <- AD0[, i + 4L * (seq_len(ncol(AD0) / 4) - 1L)]
# }
# 
# DP <-
#   map(seq_along(alt), \(i) {
#       AD[,i, 1] +  AD[,i, alt[i]]
#   }) %>%
#   do.call(cbind, .) %>%
#   set_rownames(seqGetData(gds, 'sample.id')) %>%
#   set_colnames(seqGetData(gds, 'variant.id'))
# 
# med_dp_site <- apply(DP, 2, median)
# 
# BAF <-
#   map(seq_along(alt), \(i) {
#      baf <- AD[,i, alt[i]] / DP[,i]
#      pmin(baf, 1-baf)
#   }) %>%
#   do.call(cbind, .) %>%
#   set_rownames(seqGetData(gds, 'sample.id')) %>%
#   set_colnames(seqGetData(gds, 'variant.id'))
# 
# 
# BAF <- BAF[, abs(scale(med_dp_site)) < 2]

# baf_smry <-
#   rowMeans(BAF, na.rm = T) %>% 
#   tibble::enframe(name = 'sample',
#                   value = 'mean_baf')
# 
# saveRDS(baf_smry, '1.work/baf_smry.rds')

baf_smry <- readRDS('1.work/baf_smry.rds')

```

```{r find_likely_non_mixed}
# set threshold at quartile Q3 of BAF for samples not predicted as mixed by any method
# consider all samples with mean BAF less than threshold as unmixed

baf_pred_smry <-
  baf_smry %>% 
  left_join(pred_100X_smry, by = 'sample') %>% 
  mutate(n_pred_mix = as.factor(n_pred_mix))

thresh_q3 <-
  baf_pred_smry %>% 
  filter(n_pred_mix == 0) %>% 
  pull(mean_baf) %>% 
  quantile(p = 0.75)

baf_pred_smry %>% 
  ggplot(aes(n_pred_mix, mean_baf)) +
  geom_violin(scale = 'width') +
  geom_boxplot(outlier.alpha = 0.2) +
  geom_hline(yintercept = thresh_q3, col = 'red')

nonmixed <-
  baf_smry %>% 
  filter(mean_baf < thresh_q3) %>% 
  select(sample)

```


```{r sample_combinations}
# gds <- seqOpen('in_silico_data/in_silico_bench.concat.gds', allow.duplicate = T)
# seqSetFilter(gds, sample.id = nonmixed$sample)
# snp_dist <-  TBtypeR:::snp_distance(gds)
# saveRDS(snp_dist, '1.work/snp_dist.rds')

# snp_dist_mat <- as.matrix(readRDS('1.work/snp_dist.rds'))

## avoid sample combinations where snp_distance < 10
# sample_combs <-
#   as.matrix(snp_dist) %>% 
#   as.data.frame() %>% 
#   rownames_to_column('sample_1') %>% 
#   pivot_longer(-sample_1, names_to = 'sample_2', values_to = 'dist') %>% 
#   filter(dist >= 10) %>% 
#   select(-dist)

# saveRDS(sample_combs, '1.work/sample_combs.rds')

sample_combs <- readRDS('1.work/sample_combs.rds')
```


```{r generate_mixtures}
depths <- c(20, 40, 60, 80, 100)
props <- c(1,2.5,5,10,25,50)/100
n_samples <- 50
counts <- rep(0L, nrow(nonmixed)) %>% setNames(nonmixed$sample)
weights <- rep(1L, nrow(nonmixed))

# in_silico_dataset <-
#   expand_grid(depth = depths,
#               prop_2 = props) %>% 
#   mutate(prop_1 = 1 - prop_2, 
#          .before = 'prop_2') %>%
#   mutate(samples = map(row_number(), function(s) {
#     set.seed(s)
#     
#     S1S2 <-
#       sample_n(nonmixed, n_samples, weight = weights) %>% 
#       rename(sample_1 = sample) %>% 
#       left_join(sample_combs, by = join_by(sample_1)) %>% 
#       sample_n(n()) %>% 
#       group_by(sample_1) %>% 
#       slice(1) %>% 
#       ungroup()
#     # balance chance of being sample_1
#     counts[S1S2$sample_1] <<- counts[S1S2$sample_1] + 1000
#     weights <<- abs(counts - max(counts)) + 1
#     
#     # find sample_3 compatible with sample_1 and sample_2
#     S1S2S3 <-
#       inner_join(
#       sample_combs %>% 
#         semi_join(S1S2, by = 'sample_1') %>% 
#         rename(sample_3 = sample_2) %>% 
#         inner_join(S1S2, by = 'sample_1'),
#       sample_combs %>% 
#         rename(sample_2 = sample_1, sample_3 = sample_2) %>% 
#         semi_join(S1S2, by = 'sample_2') %>% 
#         inner_join(S1S2, by = 'sample_2', relationship = "many-to-many"),
#       by = join_by(sample_1, sample_2, sample_3)) %>% 
#       sample_n(n()) %>% 
#       group_by(sample_1) %>% 
#       slice(1) %>% 
#       ungroup() %>% 
#       select(sample_1, sample_2, sample_3)
#     
#     
# 
#   })) %>% 
#   unnest(samples) %>% 
#   mutate(id = row_number())  %>% 
#   (function(x) bind_rows(
#     #SINGLE
#     mutate(x, id = str_c('SING', str_pad(id, 4, 'left', '0'))) %>% 
#       select(-c(sample_2, sample_3, prop_2)) %>% 
#       mutate(prop_1 = 1),
#     # PAIRS
#     mutate(x, id = str_c('PAIR', str_pad(id, 4, 'left', '0'))) %>% 
#       select(-sample_3),
#     #TRIOS
#     mutate(x, id = str_c('TRIO', str_pad(id, 4, 'left', '0'))) %>% 
#       filter(prop_2 ==  0.50) %>% 
#       mutate(prop_2 = 1/3,
#              prop_3 = 1/6),
#     
#   )) %>% 
#   select(id, depth, prop_1, prop_2, prop_3, sample_1, sample_2, sample_3) 

# sdist <- \(x, y) `if`(is.na(x) | is.na(y), NA_integer_, snp_dist_mat[x, y])
# 
# in_silico_dataset <-
#   in_silico_dataset %>% 
#   mutate(
#     dist_1_2 = map2_int(sample_1, sample_2, sdist),
#     dist_1_3 = map2_int(sample_1, sample_3, sdist),
#     dist_2_3 = map2_int(sample_2, sample_3, sdist)
#   )
# saveRDS(in_silico_dataset, '1.work/in_silico_dataset.rds')

in_silico_dataset <- read_rds('1.work/in_silico_dataset.rds')



```

```{r gen_mix_workflow}

if (!dir.exists('1.work/gen_mix')) {
  dir.create('1.work/gen_mix')
}
# create manifest for mixing
in_silico_dataset %>% 
  pivot_longer(-c(id, depth),
               names_to = c('.value', 'num'),
               names_pattern = '(.+)_([123])') %>% 
  filter(!is.na(sample)) %>% 
  inner_join(
    samples_input %>% 
      select(sample=sample_id, median_depth, fastq1, fastq2),
    by = join_by(sample)
  ) %>% 
  mutate(frac = prop * depth / median_depth,
         seed = 1) %>% 
  rename(fq1 = fastq1, fq2 = fastq2) %>% 
  select(id, sample, frac, seed, fq1, fq2) %>% 
  write_tsv('1.work/gen_mix/manifest.tsv')
# run through './TBpipeR/workflows/benchmarking/FastqMixer/main.nf'

```


```{r run_benchmarks}

if (!dir.exists('1.work/benchmark')) {
  dir.create('1.work/benchmark')
}
# copy nextflow config
file.copy('nextflow.config', '1.work/benchmark/')
# copy ref
file.copy(ref_fn, '1.work/benchmark/')
# create manifest
read_tsv('1.work/gen_mix/output/output_manifest.tsv') %>% 
  rename(sample = id) %>% 
  arrange_all() %>% 
  write_tsv('1.work/benchmark/manifest.tsv')
# run through TBpipeR Benchmark suite - nextflow run ./TBpipeR/main.nf

#### TO DO  ##########################
# GET TRACE DATA (TIME, CPU, MEMORY) 
# FROM BENCHMARK IN CASE 
# REVIEWERS ASK FOR IT
######################################
```

```{r import_result}
# bench_res_raw <- read_tsv('./1.work/benchmark/output/combined_results.tsv')
# saveRDS(bench_res_raw, './1.work/bench_res_raw.rds')

bench_res_raw <- readRDS('./1.work/bench_res_raw.rds')

# ensure that no sample/method combinations missing
missing <-
  bench_res_raw %>% 
  select(method, sample) %>% 
  distinct() %>% 
  mutate(present = TRUE) %>% 
  group_by(method) %>% 
  complete(sample = in_silico_dataset$id) %>% 
  ungroup() %>% 
  mutate(present = replace_na(present, FALSE)) %>% 
  filter(!present)

```

```{r nextflow_trace}
to_giga <- function(x) {
    mult <- case_when(
      str_detect(x, ' GB') ~ 1000**0,
      str_detect(x, ' MB') ~ 1000**-1,
      str_detect(x, ' KB') ~ 1000**-2,
      str_detect(x, ' B')  ~ 1000**-3,
      TRUE ~ NA_real_
    )
    as.numeric(str_extract(x, '[0-9\\.]+'))*mult
}
# 
# duration/realtime in secounds
# peak_rss, peak_vmem, rchar, wchar in GB
# read_tsv('./1.work/benchmark/trace-20240129-59789472.txt') %>%
#   janitor::clean_names() %>%
#   mutate(
#     across(c(duration, realtime),
#            \(x) { str_to_upper(x) %>% lubridate::as.duration() %>% as.numeric() }),
#     percent_cpu = str_remove(percent_cpu, '%') %>% as.numeric(),
#     across(c(peak_rss, peak_vmem, rchar, wchar), to_giga)
#   ) %>%
#   mutate(
#     tool = str_extract(name, '(?<=Benchmark:).+(?=:)'),
#     process = str_extract(name, '(?<=Benchmark:[^:]{1,20}:).+(?=\\s)'),
#     id = str_extract(name, '(?<=\\().+(?=\\))'),
#     .after = name
#   ) %>%
#   select(tool, process, id, duration, realtime, percent_cpu, peak_rss, peak_vmem, rchar, wchar) %>%
#   arrange(tool, process, id) %>%
#   mutate(across(c(tool, process, id), as.factor)) %>% 
#   saveRDS('1.work/nxf_trace.rds')

nxf_trace <- readRDS('1.work/nxf_trace.rds')
```



