---
title: "TBtyper simulations"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(furrr)
future::plan(future::multiprocess, workers = 16)
```

```{r optim_phy_mix}
if (file.exists('optim_phy_mix_tests.rds')) {
  optim_phy_mix_tests <- readRDS('optim_phy_mix_tests.rds')
} else {
  optim_phy_mix_tests <-
    expand_grid(mix_n = 2:4, mean_depth = c(10, 50, 100)) %>%
    mutate(res = future_pmap(., function(mix_n, mean_depth, pseudocounts) {
      TBtyper:::test_optim_phy_mix(mix_n = mix_n,
                                   mean_depth = mean_depth,
                                   err_rate = 0.50,
                                   err_p = 0.01,
                                   n_test = 1000L,
                                   pseudo = 'compare')
    })) %>%
    unnest(res)
  saveRDS(optim_phy_mix_tests, 'optim_phy_mix_tests.rds')
}

# optim_phy_mix_tests %>% 
#   filter(pseudocounts) %>% 
#   rename(depth = mean_depth) %>% 
#   ggplot(aes(mix_prop, est_prop)) +
#   geom_abline(slope = 1, intercept = 0, col = 'red') +
#   geom_point(alpha = 0.10, size = 0.75) +
#   coord_fixed() +
#   theme(axis.text.x = element_text(angle= 90)) +
#   facet_grid(depth ~ mix_n, labeller = 'label_both')
# 
# optim_phy_mix_tests %>% 
#   filter(pseudocounts) %>% 
#   rename(depth = mean_depth) %>% 
#   mutate(err = 100 * (est_prop - mix_prop),
#          mix_index = as.factor(mix_index)) %>% 
#   ggplot(aes(mix_index, err)) +
#   geom_violin() +
#   stat_summary(fun.y = 'mean', geom = 'line', size = 0.75, group = 1, col = 'red', alpha = 0.75) +
#   stat_summary(fun.y = 'mean', geom = 'point', size = 0.75) +
#   theme(axis.text.x = element_text(angle= 90)) +
#   ylab('error (%)') + 
#   xlab('mix proportion rank') +
#   ylim(-10, 10) +
#   ggtitle('with pseudocounts') + 
#   facet_grid(depth ~ mix_n, labeller = 'label_both')
# 
# optim_phy_mix_tests %>% 
#   filter(!pseudocounts) %>% 
#   rename(depth = mean_depth) %>% 
#   mutate(err = 100 * (est_prop - mix_prop),
#          mix_index = as.factor(mix_index)) %>% 
#   ggplot(aes(mix_index, err)) +
#   geom_violin() +
#   stat_summary(fun.y = 'mean', geom = 'line', size = 0.75, group = 1, col = 'red', alpha = 0.75) +
#   stat_summary(fun.y = 'mean', geom = 'point', size = 0.75) +
#   theme(axis.text.x = element_text(angle= 90)) +
#   ylab('error (%)') + 
#   xlab('mix proportion rank') +
#   ylim(-10, 10) +
#   ggtitle('no pseudocounts') + 
#   facet_grid(depth ~ mix_n, labeller = 'label_both')

```


```{r d_pseudo_binom}
d_pseudo_binom <- function(x, size, prob, log = FALSE, pseudocount = 1L) {
  pseudorate <- pseudocount / (size + 2L * pseudocount)
  adj_prob <- prob * (1 - pseudorate) + pseudorate * (1 - prob)
  return(dbinom(x + pseudocount, size + 2L * pseudocount, adj_prob, log))
}

res <- 
  expand_grid(size = c(10, 100, 1000),
              prob = c(0.1, 0.2, 0.3, 0.4, 0.5)) %>% 
  mutate(x = map(size, ~ seq_len(. + 1) - 1)) %>% 
  unnest(x) %>% 
  mutate(log_lh_binom = dbinom(x, size, prob, log = F),
         log_lh_pseudo_binom = d_pseudo_binom(x, size, prob, log = F))

res %>% 
  group_by(size, prob) %>% 
  mutate_at(vars(log_lh_binom, log_lh_pseudo_binom), ~ rank(.)) %>% 
  ggplot(aes(log_lh_binom, log_lh_pseudo_binom)) +
  geom_point() +
  facet_wrap(size ~ prob,scales = 'free')


res %>% 
  group_by(size, prob) %>% 
  mutate_at(vars(log_lh_binom, log_lh_pseudo_binom), ~ rank(.)) %>% 
  filter(size == 100, prob == 0.2) %>% 
  ggplot(aes(log_lh_binom, log_lh_pseudo_binom)) +
  geom_point()

```

```{r}
x <- expand_grid(x = 0:1,
            size = c(2, 5, 10, 50),
            point = 0:20) %>% 
  mutate(p = (1 / size) * (point/10),
         lh = dbinom(x, size, p),
         x = ordered(x), 
         point = ordered(point)) %>% 
  ggplot(aes(point, lh, col = x, group = x)) +
  scale_color_viridis_d(end = 0.8) +
  geom_line() +
  geom_point() +
  facet_wrap(~ size)


```
