---
title: "TB in vitro mixture dataset"
output: 'github_document'
---


```{r setup}
library(SeqArray)
library(tidyverse)
library(magrittr)
```


```{r mi_1, eval=FALSE}
# MixInfect - https://doi.org/10.1186/s12864-018-4988-z
# pull table from pub using rvest
url <-  "https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4988-z/tables/1"
rvest::read_html(url) %>%
  rvest::html_nodes("table") %>%
  rvest::html_table(fill = T) %>%
  first() %>%
  (\(x) set_colnames(x[-1,], c(x[1,]))) %>%
  janitor::clean_names() %>%
  readr::type_convert() %>%
  saveRDS('1.work/mi_tab_1.rds')
```

```{r mi_2}
mi_tab_1 <- readRDS('1.work/mi_tab_1.rds')
```

```{r create_downloader_script, eval=FALSE}
PARALLEL = 8
str_c(
  '#!/usr/bin/env bash',
  '# requires sra-toolkit fasterq-dump',
  str_c('echo "', str_c(mi_tab_1$sample_identifier, collapse = ' '), '" |'),
  '\ttr \' \' \'\\n\' |',
  str_c('\txargs -n1 -P', PARALLEL, ' -i bash -c "fasterq-dump -3 {} && gzip {}_1.fastq && gzip {}_2.fastq"'),
  sep = '\n') %>% 
  write_lines('0.fasterq_dump.sh')
```

```{r ss_1, eval=FALSE}
# SplitStrains - https://doi.org/10.1099/mgen.0.000607

mgen_0_000607_supp_url <- 'https://ndownloader.figstatic.com/files/28367802'
mgen_0_000607_supp_fn <- file.path('1.work', 'MGEN_0_00067_supp.xlsx')
if (!file.exists(ref_fn)) { download.file(mgen_0_000607_supp_url, mgen_0_000607_supp_fn) }

# excel has converted this columrn to dates which
lin_date_fix <- c(
  '1/1' = 43831, '2/2' = 43863, '4/3' = 43924, '3/4' = 43894,'4/4' = 43925,
  '1/3' = 43833, '3/1' = 43891, '2/4' = 43865, '4/2' = 43923
)

suppressWarnings(readxl::read_excel(ref_fn, sheet = 'Dataset A', skip = 3)) %>%
  janitor::clean_names() %>%
  mutate(major_minor_lineage = if_else(
    major_minor_lineage %in% lin_date_fix,
    names(lin_date_fix)[match(major_minor_lineage, lin_date_fix)],
    as.character(major_minor_lineage)
  )) %>%
  nest(split_strains = 7:9,
       mixed_infection_estimator = 10:11,
       quant_tb = 12:13,
       mix_infect = 14:19) %>%
  saveRDS('1.work/ss_sup_tab.rds')
```

```{r ss_2}
ss_sup_tab <- readRDS('1.work/ss_sup_tab.rds')
```

```{r check_table_equivalence}
diffdf::diffdf(
  mi_tab_1 %>% 
    select(id = sample_identifier,
           maj_prop = major_strain_proportion,
           lin = major_minor_strain_lineage) %>% 
    arrange_all(),
  ss_sup_tab %>% 
    select(id = id,
           maj_prop = major_proportion,
           lin = major_minor_lineage) %>% 
    arrange_all()
)
```
```{r download_ref}
ref_url <- 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/195/955/GCA_000195955.2_ASM19595v2/GCA_000195955.2_ASM19595v2_genomic.fna.gz'
ref_fn <- file.path('1.work', basename(ref_url))
if (!file.exists(ref_fn)) { download.file(ref_url, ref_fn) }
```


```{r run_benchmarks, eval=FALSE}
# run 0.fasteq_dump.sh to download all fastqs first
input_fastq_dir <- './fastq'

# create directory to run through all tools in  TBpipeR benchmark
if (!dir.exists('1.work/benchmark')) {
  dir.create('1.work/benchmark')
}

# write manifest
tibble(
  fastq1 = list.files(normalizePath(input_fastq_dir), pattern = '_1.fastq.gz', full.names = T),
  fastq2 = list.files(normalizePath(input_fastq_dir), pattern = '_2.fastq.gz', full.names = T)) %>% 
  mutate(
    sample = str_extract(basename(fastq1), '[^_]+'),
    .before = fastq1) %>% 
  write_tsv('1.work/benchmark/manifest.tsv')

# copy nextflow config
file.copy('nextflow.config', '1.work/benchmark/')
# copy ref
file.copy(ref_fn, '1.work/benchmark/')

# run through TBpipeR Benchmark suite - nextflow run ./TBpipeR/main.nf

# save results as RDS
read_tsv('1.work/benchmark/output/combined_results.tsv') %>%
  saveRDS('1.work/iv_bench_res_raw.rds')

read_tsv('1.work/benchmark/output/SplitStrains.results.tsv') %>% 
  janitor::clean_names() %>% 
  rename(sample = file) %>% 
  mutate(sample = str_remove(sample, '.bam')) %>% 
  saveRDS('1.work/iv_bench_splitstrains_res_raw.rds')
```


```{r run_benchmarks}
iv_bench_res_raw <- readRDS('1.work/iv_bench_res_raw.rds')
iv_bench_splitstrains_res_raw <- readRDS('1.work/iv_bench_splitstrains_res_raw.rds')
```

