---
title: "TB in vitro mixture dataset"
output: 'github_document'
---


```{r setup}
library(tidyverse)
```

```{r download_mixinfect, eval=FALSE}
# MixInfect - https://doi.org/10.1186/s12864-018-4988-z
# pull table from pub using rvest
url <-  "https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4988-z/tables/1"
rvest::read_html(url) %>%
  rvest::html_nodes("table") %>%
  rvest::html_table(fill = T) %>%
  first() %>%
  (\(x) set_colnames(x[-1,], c(x[1,]))) %>%
  janitor::clean_names() %>%
  readr::type_convert() %>%
  saveRDS('02/mi_tab_1.rds')
```

```{r download_splitstrains, eval=FALSE}
# SplitStrains - https://doi.org/10.1099/mgen.0.000607

mgen_0_000607_supp_url <- 'https://ndownloader.figstatic.com/files/28367802'
mgen_0_000607_supp_fn <- file.path('02', 'MGEN_0_00067_supp.xlsx')
print(file.exists(mgen_0_000607_supp_fn))
if (!file.exists(mgen_0_000607_supp_fn)) { download.file(mgen_0_000607_supp_url, mgen_0_000607_supp_fn) }
# 
# excel has converted this columrn to dates which
lin_date_fix <- c(
  '1/1' = 43831, '2/2' = 43863, '4/3' = 43924, '3/4' = 43894,'4/4' = 43925,
  '1/3' = 43833, '3/1' = 43891, '2/4' = 43865, '4/2' = 43923
)

suppressWarnings(readxl::read_excel(mgen_0_000607_supp_fn, sheet = 'Dataset A', skip = 3)) %>%
  janitor::clean_names() %>%
  mutate(major_minor_lineage = if_else(
    major_minor_lineage %in% lin_date_fix,
    names(lin_date_fix)[match(major_minor_lineage, lin_date_fix)],
    as.character(major_minor_lineage)
  )) %>%
  nest(split_strains = 7:9,
       mixed_infection_estimator = 10:11,
       quant_tb = 12:13,
       mix_infect = 14:19) %>%
  saveRDS('02/ss_sup_tab.rds')
```

```{r download_ref, eval=FALSE}
ref_url <- 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/195/955/GCA_000195955.2_ASM19595v2/GCA_000195955.2_ASM19595v2_genomic.fna.gz'
ref_fn <- file.path('02', basename(ref_url))
if (!file.exists(ref_fn)) { download.file(ref_url, ref_fn) }
```
```{bash download_fastqs, eval=FALSE}
mkdir -p './02/fastq'
cd './02/fastq'
bash 00.fasterq_dump.in_vitro.sh
```
```{r prep_benchmark, eval=FALSE}
# run 0.fasteq_dump.sh to download all fastqs first
input_fastq_dir <- './02/fastq'

# create directory to run through all tools in  TBpipeR benchmark
if (!dir.exists('02/benchmark')) {
  dir.create('02/benchmark')
}

# write manifest
tibble(
  fastq1 = list.files(normalizePath(input_fastq_dir), pattern = '_1.fastq.gz', full.names = T),
  fastq2 = list.files(normalizePath(input_fastq_dir), pattern = '_2.fastq.gz', full.names = T)) %>% 
  mutate(
    sample = str_extract(basename(fastq1), '[^_]+'),
    .before = fastq1) %>% 
  write_tsv('02/benchmark/manifest.tsv')

# copy nextflow config
file.copy('benchmark_default.config', '02/benchmark/nextflow.config')
# copy ref
file.copy(ref_fn, '02/benchmark/')
```

```{bash run_benchmark, eval=FALSE}
cd "02/benchmark"
nextflow run ../../TBpipeR/main.nf
```

```{r prep_benchmark_var, eval=FALSE}
# copy nextflow config
file.copy('benchmark_variation.config', '02/benchmark/nextflow.config', overwrite = T)

# conver TBtypeR panel to Fastlin and TBProfiler formats
TBtypeR:::make_fastlin_bc(
  '02/benchmark/tbt_fastlin_barcode.tsv',
  ref_fasta = '02/GCA_000195955.2_ASM19595v2_genomic.fna.gz',
  mode = 'fastlin')
TBtypeR:::make_tbprofiler_bc('04/benchmark/tbt_tbprofiler_barcode.bed')
```

```{bash run_benchmark_var, eval=FALSE}
cd "04/benchmark"
nextflow run ../../TBpipeR/main.nf
```

```{r save_bench_results, eval=FALSE}
read_tsv('02/benchmark/output/combined_results.tsv') %>% 
  saveRDS('02/iv_bench_res_raw.rds')

read_tsv('02/benchmark/output/SplitStrains.results.tsv') %>% 
  janitor::clean_names() %>% 
  rename(sample = file) %>% 
  mutate(sample = str_remove(sample, '.bam$')) %>% 
  saveRDS('02/iv_splitstrains_res_raw.rds')
```

```{r optim_splitstrains, eval=FALSE}
mi_tab_1 <- readRDS('02/mi_tab_1.rds')
iv_splitstrains_res_raw <- readRDS('02/iv_splitstrains_res_raw.rds')

# the authors of SplitStrains provide no guidelines on the LR_statistic threshold, so find empiricly
splitstrain_thresh <-
  iv_splitstrains_res_raw %>% 
  select(sample, lr_statistic) %>% 
  (function(x) {
    x %>% 
      transmute(thresh = lr_statistic) %>% 
      distinct() %>% 
      expand_grid(x)
  }) %>% 
  mutate(is_mixed_pred = lr_statistic > thresh) %>% 
  left_join(
    mi_tab_1 %>% 
      mutate(is_mixed = major_strain_proportion < 1) %>% 
      select(sample = sample_identifier, is_mixed)
  ) %>% 
  group_by(thresh) %>% 
  summarise(measures = binary_measures(is_mixed, is_mixed_pred)) %>% 
  unnest(measures) %>% 
  slice(which.max(nMCC)) %>% 
  pull(thresh)
# Note: include in nextflow config and resume benchmark in 02.prep_data_in_vitro.Rmd
message("Optimal Splitstrains LR_Statistc threshold: ", splitstrain_thresh)
```

```{r save_bench_results_2, eval=FALSE}
read_tsv('02/benchmark/output/combined_results.tsv') %>% 
  saveRDS('02/iv_bench_res_raw.rds')

read_tsv('02/benchmark/output-var/combined_results.tsv') %>% 
  saveRDS('02/iv_bench_res_var_raw.rds')
```
