---
title: "TB in silico mixture dataset"
output: 'github_document'
---

```{r setup}
library(tidyverse)
```

```{r download_ref, eval=FALSE}
ref_url <- 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/195/955/GCA_000195955.2_ASM19595v2/GCA_000195955.2_ASM19595v2_genomic.fna.gz'
ref_fn <- file.path('04', basename(ref_url))
if (!file.exists(ref_fn)) { download.file(ref_url, ref_fn) }
```

```{bash download_fastqs, eval=FALSE}
mkdir -p './04/fastq'
cd './04/fastq'
bash 01.fasterq_dump.in_silico.sh
```

```{r input_samples}
# run 0.fasteq_dump.sh to download all fastqs first
# set to directory of FASTQs from SRA-tools fastq-dump on your system
input_fastq_dir <- './04/fastq'

# 950 random samples from DOI:10.1056/NEJMoa1800474 with:
  # platform == Illumina HiSeq 2500
  # median_depth >= 100
  # fastp_pct_pass >= 95
  # pct_mapped >= 95
  # read lengths >= 290

samples_input <- 
  read_rds('04/nejmoa1800474_subset_metadata.rds') %>% 
  mutate(
    fastq1 = file.path(normalizePath(input_fastq_dir), str_c(sample_id, '_1.fastq.gz')),
    fastq2 = file.path(normalizePath(input_fastq_dir), str_c(sample_id, '_2.fastq.gz'))
  )
```


* downsample all to 100X
* run though all methods
```{r prep_downsample, eval=FALSE}
# downsample all files to 100X coverage for consistency
if (!dir.exists('04/downsample')) {
  dir.create('04/downsample')
}
# create manifest for downsampling
samples_input %>% 
  transmute(id = str_c(sample_id, '_100X'),
            sample = sample_id,
            frac = 100 / median_depth,
            seed = 1,
            fq1 = fastq1,
            fq2 = fastq2) %>% 
  write_tsv('04/downsample/manifest.tsv')
## cd '04/downsample/manifest.tsv' and run nextflow ./TBpipeR/workflows/benchmarking/FastqMixer/main.nf'
```

```{bash run_downsampling, eval=FALSE}
cd "04/downsample"
nextflow run ../../TBpipeR/workflows/benchmarking/FastqMixer/main.nf
```


```{r predict_at_100X, eval=FALSE}
# create directory to run through all tools in  TBpipeR benchmark
if (!dir.exists('04/100X_pred')) {
  dir.create('04/100X_pred')
}
# copy nextflow config
file.copy('benchmark_default.config', '04/100X_pred/nextflow.config')
# copy ref
file.copy(ref_fn, '04/100X_pred/')
# create manifest
read_tsv('04/downsample/output/output_manifest.tsv') %>% 
  rename(sample = id) %>% 
  mutate(sample = str_remove(sample, '_100X')) %>% 
  write_tsv('04/100X_pred/manifest.tsv')
# run through TBpipeR Benchmark suite - nextflow run ./TBpipeR/main.nf
```

```{bash run_benchmark, eval=FALSE}
cd "04/100X_pred"
nextflow run ../../TBpipeR/main.nf
```

```{r predict_at_100X_2, eval=FALSE}
# save results as RDS
read_tsv('04/100X_pred/output/combined_results.tsv')  %>% 
  saveRDS('04/100X_combined_results.rds')
```

```{r predictions_at_100X}
# read_rds('04/100X_combined_results.rds') %>%  View()
pred_100X <- 
  read_rds('04/100X_combined_results.rds') %>% 
  group_by(method, sample) %>% 
  summarise(n_mix = n(), 
            minor_prop = 1 - max(proportion, na.rm = T),
            .groups = 'drop')

pred_100X_smry <-
  pred_100X %>% 
  group_by(sample) %>% 
  summarise(n_pred_mix = sum(n_mix > 1))
```


```{r sample_BAF, eval=FALSE}
library(SeqArray)

gds <- seqOpen('04/100X_pred/output/gds/benchmark.concat.gds', allow.duplicate = T)
af <- map(0:3, ~seqAlleleFreq(gds, ref.allele = .)) %>% do.call(cbind, .)
# remove sites with no alt alleles
include <- af[,1] < 1
SeqArray::seqSetFilter(gds, variant.sel =include)
# determine which alt allele is most common
alt <- map_int(seq_len(nrow(af)), \(x) which.max(af[x,-1]))[include] + 1

AD0 <- seqGetData(gds, 'annotation/format/AD')$data
AD <- array(integer(), dim = c(nrow(AD0), ncol(AD0)/4, 4))
for (i in seq(4)) {
  AD[, , i] <- AD0[, i + 4L * (seq_len(ncol(AD0) / 4) - 1L)]
}

DP <-
  map(seq_along(alt), \(i) {
      AD[,i, 1] +  AD[,i, alt[i]]
  }) %>%
  do.call(cbind, .) %>%
  set_rownames(seqGetData(gds, 'sample.id')) %>%
  set_colnames(seqGetData(gds, 'variant.id'))

med_dp_site <- apply(DP, 2, median)

BAF <-
  map(seq_along(alt), \(i) {
     baf <- AD[,i, alt[i]] / DP[,i]
     pmin(baf, 1-baf)
  }) %>%
  do.call(cbind, .) %>%
  set_rownames(seqGetData(gds, 'sample.id')) %>%
  set_colnames(seqGetData(gds, 'variant.id'))

BAF <- BAF[, abs(scale(med_dp_site)) < 2]

baf_smry <-
  rowMeans(BAF, na.rm = T) %>%
  tibble::enframe(name = 'sample',
                  value = 'mean_baf')

saveRDS(baf_smry, '04/baf_smry.rds')
```

```{r find_likely_non_mixed}
# set threshold at quartile Q3 of BAF for samples not predicted as mixed by any method
# consider all samples with mean BAF less than threshold as unmixed
baf_smry <- readRDS('04/baf_smry.rds')

baf_pred_smry <-
  baf_smry %>% 
  left_join(pred_100X_smry, by = 'sample') %>% 
  mutate(n_pred_mix = as.factor(n_pred_mix))

thresh_q3 <-
  baf_pred_smry %>% 
  filter(n_pred_mix == 0) %>% 
  pull(mean_baf) %>% 
  quantile(p = 0.75)

nonmixed <-
  baf_smry %>% 
  filter(mean_baf < thresh_q3) %>% 
  select(sample)


baf_pred_smry %>% 
  ggplot(aes(n_pred_mix, mean_baf)) +
  geom_violin(scale = 'width') +
  geom_boxplot(outlier.alpha = 0.2) +
  geom_hline(yintercept = thresh_q3, col = 'red') +
  scale_y_continuous(trans = 'log10')

```


```{r sample_combinations, eval=FALSE}
gds <- seqOpen('04/100X_pred/output/gds/benchmark.concat.gds', allow.duplicate = T)
seqSetFilter(gds, sample.id = nonmixed$sample)
snp_dist <-  TBtypeR:::snp_distance(gds)

snp_dist_mat <- as.matrix(snp_dist)

# avoid sample combinations where snp_distance < 10
sample_combs <-
  as.matrix(snp_dist) %>%
  as.data.frame() %>%
  rownames_to_column('sample_1') %>%
  pivot_longer(-sample_1, names_to = 'sample_2', values_to = 'dist') %>%
  filter(dist >= 10) %>%
  select(-dist)

saveRDS(sample_combs, '04/sample_combs.rds')
```

```{r generate_mixtures, eval=FALSE}
depths <- c(20, 40, 60, 80, 100)
props <- c(1,2.5,5,10,25,50)/100
n_samples <- 50
counts <- rep(0L, nrow(nonmixed)) %>% setNames(nonmixed$sample)
weights <- rep(1L, nrow(nonmixed))
sample_combs <- readRDS('04/sample_combs.rds')

in_silico_dataset <-
  expand_grid(depth = depths,
              prop_2 = props) %>%
  mutate(prop_1 = 1 - prop_2,
         .before = 'prop_2') %>%
  mutate(samples = map(row_number(), function(s) {
    set.seed(s)

    S1S2 <-
      sample_n(nonmixed, n_samples, weight = weights) %>%
      rename(sample_1 = sample) %>%
      left_join(sample_combs, by = join_by(sample_1)) %>%
      sample_n(n()) %>%
      group_by(sample_1) %>%
      slice(1) %>%
      ungroup()
    # balance chance of being sample_1
    counts[S1S2$sample_1] <<- counts[S1S2$sample_1] + 1000
    weights <<- abs(counts - max(counts)) + 1

    # find sample_3 compatible with sample_1 and sample_2
    S1S2S3 <-
      inner_join(
      sample_combs %>%
        semi_join(S1S2, by = 'sample_1') %>%
        rename(sample_3 = sample_2) %>%
        inner_join(S1S2, by = 'sample_1'),
      sample_combs %>%
        rename(sample_2 = sample_1, sample_3 = sample_2) %>%
        semi_join(S1S2, by = 'sample_2') %>%
        inner_join(S1S2, by = 'sample_2', relationship = "many-to-many"),
      by = join_by(sample_1, sample_2, sample_3)) %>%
      sample_n(n()) %>%
      group_by(sample_1) %>%
      slice(1) %>%
      ungroup() %>%
      select(sample_1, sample_2, sample_3)



  })) %>%
  unnest(samples) %>%
  mutate(id = row_number())  %>%
  (function(x) bind_rows(
    #SINGLE
    mutate(x, id = str_c('SING', str_pad(id, 4, 'left', '0'))) %>%
      select(-c(sample_2, sample_3, prop_2)) %>%
      mutate(prop_1 = 1),
    # PAIRS
    mutate(x, id = str_c('PAIR', str_pad(id, 4, 'left', '0'))) %>%
      select(-sample_3),
    #TRIOS
    mutate(x, id = str_c('TRIO', str_pad(id, 4, 'left', '0'))) %>%
      filter(prop_2 ==  0.50) %>%
      mutate(prop_2 = 1/3,
             prop_3 = 1/6),

  )) %>%
  select(id, depth, prop_1, prop_2, prop_3, sample_1, sample_2, sample_3)

sdist <- \(x, y) `if`(is.na(x) | is.na(y), NA_integer_, snp_dist_mat[x, y])

in_silico_dataset <-
  in_silico_dataset %>%
  mutate(
    dist_1_2 = map2_int(sample_1, sample_2, sdist),
    dist_1_3 = map2_int(sample_1, sample_3, sdist),
    dist_2_3 = map2_int(sample_2, sample_3, sdist)
  )

saveRDS(in_silico_dataset, '04/in_silico_dataset.rds')
```

```{r prep_generate_mixtures, eval=FALSE}

in_silico_dataset <- read_rds('04/in_silico_dataset.rds')

if (!dir.exists('04/gen_mix')) {
  dir.create('04/gen_mix')
}
# create manifest for mixing
in_silico_dataset %>% 
  pivot_longer(-c(id, depth),
               names_to = c('.value', 'num'),
               names_pattern = '(.+)_([123])') %>% 
  filter(!is.na(sample)) %>% 
  inner_join(
    samples_input %>% 
      select(sample=sample_id, median_depth, fastq1, fastq2),
    by = join_by(sample)
  ) %>% 
  mutate(frac = prop * depth / median_depth,
         seed = 1) %>% 
  rename(fq1 = fastq1, fq2 = fastq2) %>% 
  select(id, sample, frac, seed, fq1, fq2)%>% 
  write_tsv('04/gen_mix/manifest.tsv')
```

```{bash run_generate_mixtures, eval=FALSE}
cd "04/gen_mix"
nextflow run ../../TBpipeR/workflows/benchmarking/FastqMixer/main.nf
```

```{r prep_benchmark, eval=FALSE}
if (!dir.exists('04/benchmark')) {
  dir.create('04/benchmark')
}
# copy nextflow config
file.copy('benchmark_default.config', '04/benchmark/nextflow.config')
# copy ref
file.copy(ref_fn, '04/benchmark/')
# create manifest
read_tsv('04/gen_mix/output/output_manifest.tsv') %>% 
  rename(sample = id) %>% 
  arrange_all() %>% 
  write_tsv('04/benchmark/manifest.tsv')
```


```{bash run_benchmark, eval=FALSE}
cd "04/benchmark"
nextflow run ../../TBpipeR/main.nf
```

```{r prep_benchmark_var, eval=FALSE}
# copy nextflow config
file.copy('benchmark_variation.config', '04/benchmark/nextflow.config', overwrite = T)

# conver TBtypeR panel to Fastlin and TBProfiler formats
TBtypeR:::make_fastlin_bc(
  '04/benchmark/tbt_fastlin_barcode.tsv2',
  ref_fasta = '04/GCA_000195955.2_ASM19595v2_genomic.fna.gz',
  mode = 'fastlin')
TBtypeR:::make_tbprofiler_bc('04/benchmark/tbt_tbprofiler_barcode.bed2')
```

```{bash run_benchmark_var, eval=FALSE}
cd "04/benchmark"
nextflow run ../../TBpipeR/main.nf
```

```{r prep_benchmark_time, eval=FALSE}
if (!dir.exists('04/benchmark_time')) {
  dir.create('04/benchmark_time')
}
# copy nextflow config
file.copy('benchmark_default.config', '04/benchmark_time/nextflow.config')
# copy ref
file.copy(ref_fn, '04/benchmark_time/')
# create manifest
read_tsv('04/gen_mix/output/output_manifest.tsv') %>% 
  rename(sample = id) %>% 
  arrange_all() %>% 
  filter(sample %in% {
    in_silico_dataset %>% 
      filter(depth == 60,
             str_detect(id, 'PAIR'),
             prop_1 == 0.50) %>% 
      with(c(id, str_replace_all(id, 'PAIR', 'SING')))
  }) %>% 
  arrange_all() %>% 
  write_tsv('04/benchmark_time/manifest.tsv')
```

```{bash run_benchmark_time, eval=FALSE}
cd "04/benchmark"
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
rename trace- trace-default trace-*
```

```{r prep_benchmark_time_var, eval=FALSE}
# copy nextflow config
file.copy('benchmark_variation.config', '04/benchmark_time/nextflow.config', overwrite = T)

# conver TBtypeR panel to Fastlin and TBProfiler formats
TBtypeR:::make_fastlin_bc(
  '04/benchmark_time/tbt_fastlin_barcode.tsv2',
  ref_fasta = '04/GCA_000195955.2_ASM19595v2_genomic.fna.gz',
  mode = 'fastlin')
TBtypeR:::make_tbprofiler_bc('04/benchmark_time/tbt_tbprofiler_barcode.bed2')
```

```{bash run_benchmark_time_var, eval=FALSE}
cd "04/benchmark"
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
nextflow run ../../TBpipeR/main.nf
rename trace- trace-var trace-2*
```
