---
title: "TB in vitro mixture dataset"
output: 'github_document'
---


```{r setup}
library(tidyverse)
bench_res_raw <- read_rds('03_data/bench_res_raw.rds')
in_silico_dataset <- read_rds('02_data/in_silico_dataset.rds') 

if (!dir.exists('05_data')) { dir.create('05_data') }
```

```{r table_s1, eval=FALSE}
# Q1: how similar are methods for non-mixed samples?
sing_lin <-
  bench_res_raw %>% 
  filter(str_detect(method, 'Fastlin|TBtypeR|TBProfiler'),
         !str_detect(method, '\\+FL')) %>% 
  inner_join(
    in_silico_dataset %>% 
      filter(prop_2 == 0) %>% 
      select(id, sample_1) %>% 
      group_by(sample_1) %>% 
      slice(1) %>% 
      ungroup() %>% 
      rename(sample = id, accession = sample_1),
    by = 'sample'
  ) %>% 
  group_by(sample) %>% 
  filter(all(proportion == 1)) %>% 
  ungroup() %>% 
  select(-proportion)

remap_names <- function(x, panel, renamed_panel) {
  old <- with(panel, unique(c(phylotype, parent_phylotype)))
  names(old) <- with(renamed_panel, unique(c(phylotype, parent_phylotype)))
  unname(old[x])
}

table_s1 <-
  sing_lin %>% 
  pivot_wider(names_from = method, values_from = strain) %>% 
  mutate(
    `Fastlin (+BC)` = remap_names(
      `Fastlin (+BC)`,
      TBtypeR::tbt_panel,
      TBtypeR:::rename_panel_fastlin(TBtypeR::tbt_panel)),
    `TBProfiler (+BC)` = remap_names(
      `TBProfiler (+BC)`,
      TBtypeR::tbt_panel,
      TBtypeR:::rename_panel_tbprofiler(TBtypeR::tbt_panel))
  ) %>% 
  select(accession, TBtypeR, starts_with('TBProfiler'), starts_with('Fastlin'))

# Use as Table S1
saveRDS(table_s1, '05_data/table_s1.rds')
```

```{r tbprofiler_v_Fastlin}
table_s1 <- readRDS('05_data/table_s1.rds')

# compare TBProfiler and Fastlin lineage assignement
tbp_fl_p <-
  table_s1 %>% 
  count(agree = TBProfiler == Fastlin) %>% 
  mutate(p = 100 * n / sum(n)) %>% filter(agree) %>% pull(p) %>% round(1)

message('TBProfiler and Fastlin agree ', tbp_fl_p, '%')
```

```{r tbprofiler_v_TBtypeR}
tbp_tbt_bc_p <-
  table_s1 %>% 
  count(agree = `TBProfiler (+BC)` == TBtypeR) %>% 
  mutate(p = 100 * n / sum(n)) %>% filter(agree) %>% pull(p) %>% round(1)
tbp_tbt_bc_p

message('TBProfiler (+BC) and TBtypeR agree ', tbp_tbt_bc_p, '%')
```

```{r}
# Compare TBtypeR and TBprofile lineage assignments
table_s1_status <-
  table_s1 %>% 
  pivot_longer(c(-accession, -TBtypeR),
               names_to = 'method',
               values_to = 'strain') %>% 
  mutate(status = case_when(
    TBtypeR == strain           ~ 'agrees',
    str_starts(TBtypeR, strain) ~ 'less detailed',
    str_starts(strain, TBtypeR) ~ 'more detailed',
    TRUE                        ~ 'other'
  ))

table_s1_status_p <-
  table_s1_status %>% 
  count(method, status) %>% 
  group_by(method) %>% 
  mutate(p = 100 * n / sum(n))

table_s1_status_p %>% 
  filter(method == 'TBProfiler') %>% 
  with(str_c('TBProfiler ', status,' ', round(p, 1), '%', '\n')) %>% 
  message()

table_s1_status_p %>% 
  filter(method == 'TBProfiler', str_detect(status, 'detailed'))

table_s1_status_p %>% 
  filter(method == 'TBProfiler', status == 'other')

table_s1_status %>% 
  filter(method == 'TBProfiler', status == 'other') %>% 
  count(TBtypeR, strain) %>% 
  arrange(desc(n)) 

```
