---
title: "TB in vitro mixture dataset"
output: 'github_document'
---


```{r setup}
library(tidyverse)

iv_bench_metrics <- readRDS('01_data/iv_bench_metrics.rds') %>% mutate(method = as.character(method))
is_duo_bench_metrics <- readRDS('03_data/is_duo_bench_metrics.rds') %>% mutate(method = as.character(method))
is_trio_bench_metrics <- readRDS('03_data/is_trio_bench_metrics.rds') %>% mutate(method = as.character(method))
runtime_smry <- readRDS('04_data/runtime_smry.rds')

if (!dir.exists('07_data')) { dir.create('07_data') }
```


```{r}
cols <- c('method', 'MCC', 'MAE')

pad_format <- function(x) {
  x <- format (x)
  str_pad(str_trim(x), max(nchar(x)), side = 'left', pad = '0')
}

table_1 <-
  runtime_smry %>%
  inner_join(
    iv_bench_metrics %>% 
      select(all_of(cols)),
    by = 'method',
  ) %>%
  inner_join(
    is_duo_bench_metrics %>%
      select(all_of(cols)),
    by = 'method',
    suffix = c('', '_is_duo')
  ) %>%
  inner_join(
    is_trio_bench_metrics %>%
      select(all_of(cols)),
    by = 'method',
    suffix = c('_iv', '_is_trio')
  ) %>% 
  rename_with(~ str_remove(., '1-')) %>% 
  mutate(cpu_sec = cpu_min_per_sample * 60) %>% 
  select(-cpu_min_per_sample) %>% 
  pivot_longer(-method) %>% 
  arrange(name, method) %>% 
  group_by(name) %>% 
  mutate(
    score = (value - min(value)) / (max(value) - min(value)),
    score = if_else(str_detect(name, 'MCC'), score, 1-score),
    rank = rank(desc(score), ties.method = 'min')
  ) %>% 
  group_by(method) %>% 
  mutate(comb_score = mean(score)) %>% 
  ungroup() %>% 
  chop(-c(method, comb_score)) %>% 
  mutate(comb_rank = rank(desc(comb_score),  ties.method = 'min'),
         .before = comb_score) %>% 
  arrange(comb_rank) %>% 
  mutate(comb_score = str_c(format(comb_score, digits = 3))) %>% 
  select(-score, -rank) %>% 
  rename(score = comb_score,
         rank = comb_rank) %>% 
  unchop(-c(method, score)) %>% 
  # Note - covert to percentage
  group_by(name) %>% 
  mutate(value = 
           case_when(
             str_detect(name, 'cpu') ~ pad_format(round(value, 1)),
             str_detect(name, 'MAE') ~ format(round(value, 2)),
             str_detect(name, 'MCC') ~ format(round(value, 3)),
           )
  ) %>% 
  ungroup() %>% 
  select(-rank) %>% 
  pivot_wider(names_from = name, values_from = value) %>% 
  select(method, score, MCC_iv, MAE_iv, MCC_is_duo, MAE_is_duo, MCC_is_trio, MAE_is_trio, cpu_sec) 
  
saveRDS(table_1, '07_data/table_1.rds')
writexl::write_xlsx(table_1, '07_data/Table1.xlsx')

```

