---
title: "Fig 2"
output: 'github_document'
---


```{r setup}
library(tidyverse)

if (!dir.exists('09_data')) { dir.create('09_data') }

wang_panel_A_dat <- readRDS('06_data/wang_panel_A_dat.rds')
wang_panel_B_dat <- readRDS('06_data/wang_panel_B_dat.rds')
```


```{r fig_s2_panel_a}

tool_med <- wang_panel_A_dat %>% group_by(Tool) %>% summarise(MSF = median(MSF))

fig_S2_panel_A <-
  wang_panel_A_dat %>% 
  select(Sample=sample, Tool, MSF) %>% 
  ggplot(aes(MSF, fill = Tool)) +
  geom_histogram(binwidth = 1) +
  geom_vline(
    aes(xintercept = MSF),
    data = tool_med,
    lty = 2
  ) +
  xlim(0, 50)  +
  labs(y = 'Mixed Infection Count', x = 'Minor Strain Fraction (%)')

saveRDS(fig_S2_panel_A$data, '09_data/fig_2A_data.rds')
fig_S2_panel_A
```

```{r}
wang_panel_B_dat_smry <-
  wang_panel_B_dat %>% 
  group_by(sample, set, state, exp_baf) %>% 
  summarise(
    baf = median(baf),
    .groups = 'drop'
  )

ps <- 
  map(unique(wang_panel_B_dat$set), function(SET) {
    wang_panel_B_dat %>% 
      filter(set == SET) %>% 
      ggplot(aes(state, baf)) +
      geom_hline(
        data = 
          wang_panel_B_dat_smry %>% 
          filter(set == SET),
        aes(yintercept = exp_baf),
        col = 'black',
        alpha = 0.5
      ) +
      geom_violin(
        scale = 'width',
        col = 'violet',
        fill = 'violet'
      ) +
      geom_point(
        data =
          wang_panel_B_dat_smry %>%
          filter(set == SET),
        col = 'black',
        shape = 3,
        size = 1.5,
        stroke = 0.8,
        # alpha = 0.75
      ) +
      scale_y_continuous(
        trans = scales::asn_trans(),
        limits = c(0,1),
        breaks = c(seq(0.1, 0.9, by = 0.2))
      ) +
      facet_grid(set~sample, switch = 'y') +
      labs(y = 'BAF', x = 'Genotype')
    
  })

x_blank <- theme(axis.text.x = element_blank(), axis.title.x = element_blank(), axis.ticks.x = element_blank())

nomar <- theme(
  plot.margin = margin(t=0,b=0,r=3,l=0),
  plot.title = element_text(margin = margin(t=0,b=0,r=0,l=0))
)

fig_S2_panel_B <-
  cowplot::plot_grid(
    ps[[1]] + x_blank + nomar + ggtitle('B.'),
    ps[[2]] + x_blank + nomar, 
    ps[[3]] + nomar,
    ncol = 1,
    align = 'v',
    rel_heights = c(4,4,5)
  )

fig_S2_panel_B
```

```{r fig.height=7, fig.width=8}
nomar <- theme(
  plot.margin = margin(t=0,b=0,r=3,l=0),
  plot.title = element_text(margin = margin(t=0,b=0,r=0,l=0))
)

cowplot::plot_grid(
  fig_S2_panel_A + ggtitle('A.') + nomar,
  fig_S2_panel_B,
  ncol = 1,
  rel_heights = c(5,13),
  align = 'v',
  axis = 'l'
)

cowplot::plot_grid(
  fig_S2_panel_A + ggtitle('A.') + nomar,
  ps[[1]] + x_blank + nomar + ggtitle('B.'),
  ps[[2]] + x_blank + nomar, 
  ps[[3]] + nomar,
  ncol = 1,
  rel_heights = c(8, 6.25, 5.8, 7),
  align = 'v',
  axis = 'l'
)
```

