---
title: "Fig 2"
output: 'github_document'
---


```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)

if (!dir.exists('09_data')) { dir.create('09_data') }

is_duo_by_depth_and_mp <- readRDS('03_data/is_duo_by_depth_and_mp.rds')

table_1 <- readRDS('07_data/table_1.rds')

method_order <- 
  table_1 %>%
  pull(method) %>% 
  discard(str_detect, '\\(') %>% 
  discard(str_detect, 'FastTB')
```

```{r fig_s2,  fig.height=5.5, fig.width=8}
fig_2 <- 
  is_duo_by_depth_and_mp %>% 
  filter(method %in% method_order) %>%
  mutate(
    method = factor(method, method_order),
    depth = str_c(depth, 'x Coverage') %>% 
      factor(levels = str_c(sort(unique(is_duo_by_depth_and_mp$depth)), 'x Coverage'))
  ) %>% 
  mutate(value   = if_else(measure == 'MAE', (100-value)/100, value),
         measure = if_else(measure == 'MAE', '1-MAE', measure)) %>% 
  mutate(measure = factor(measure, 
                          c('MCC','f1_score', '1-MAE', 'specificity', 'precision', 'recall', 'accuracy'))) %>% 
  filter(measure == 'MCC') %>% 
  filter(!str_detect(method, '\\(')) %>% 
  filter(!str_detect(method, 'FastT')) %>% 
  rename(Tool = method) %>% 
  ggplot(aes(minor_percent, value, colour = Tool, shape = Tool)) +
  geom_line() + 
  geom_point(aes(shape = Tool)) +
  facet_wrap(~depth,  scales='free_y') +
  scale_x_continuous(minor_breaks = NULL) +
  scale_y_continuous(minor_breaks = NULL) +
  scale_x_continuous(trans = 'log2', breaks = c(1, 2.5, 5, 10, 25, 50), minor_breaks = NULL) +
  ylab('MCC') +
  xlab('Minor Strain Fraction (%)') +
  theme(
    text = element_text(size = 8, family = 'sans'),
    plot.margin = margin(t=4, b=0, r=0, l=2),
    plot.title = element_text(margin = margin(t=0, b=0, r=0, l=0), face = 'bold')
  )


saveRDS(fig_2$data, '09_data/fig_2_data.rds')

ggsave(
  filename = '09_data/figure_2.pdf', 
  plot = fig_2, 
  width = 16, 
  height = 8, 
  units = 'cm'
)

fig_2
```
