---
title: "Fig 2"
output: 'github_document'
---


```{r setup}
library(tidyverse)

if (!dir.exists('11_data')) { dir.create('11_data') }

wang_panel_A_dat <- readRDS('06_data/wang_panel_A_dat.rds')
wang_panel_B_dat <- readRDS('06_data/wang_panel_B_dat.rds')
```


```{r fig_s2_panel_a}

tool_med <- wang_panel_A_dat %>% group_by(Tool) %>% summarise(MSF = median(MSF))

fig_4_A <-
  wang_panel_A_dat %>% 
  select(Sample=sample, Tool, MSF) %>% 
  ggplot(aes(MSF, fill = Tool)) +
  geom_histogram(binwidth = 1) +
  geom_vline(
    aes(xintercept = MSF),
    data = tool_med,
    lty = 2
  ) +
  xlim(0, 50)  +
  labs(y = 'Mixed Infection Count', x = 'Minor Strain Fraction (%)')

# saveRDS(fig_4_A$data, '11_data/fig_4A_data.rds')
fig_4_A
```

```{r}
wang_panel_B_dat_smry <-
  wang_panel_B_dat %>% 
  group_by(sample, set, state, exp_baf) %>% 
  summarise(
    baf = median(baf),
    .groups = 'drop'
  )

ps <- 
  map(unique(wang_panel_B_dat$set), function(SET) {
    wang_panel_B_dat %>% 
      filter(set == SET) %>% 
      ggplot(aes(state, baf)) +
      geom_hline(
        data = 
          wang_panel_B_dat_smry %>% 
          filter(set == SET),
        aes(yintercept = exp_baf),
        col = 'black',
        alpha = 0.5
      ) +
      geom_violin(
        scale = 'width',
        col = 'violet',
        fill = 'violet'
      ) +
      geom_point(
        data =
          wang_panel_B_dat_smry %>%
          filter(set == SET),
        col = 'black',
        shape = 3,
        size = 1.5,
        stroke = 0.8,
        # alpha = 0.75
      ) +
      scale_y_continuous(
        trans = scales::asn_trans(),
        limits = c(0,1),
        breaks = c(seq(0.1, 0.9, by = 0.2))
      ) +
      facet_grid(set~sample, switch = 'y') +
      labs(y = 'BAF', x = 'Genotype')
    
  })

x_blank <- theme(axis.text.x = element_blank(), axis.title.x = element_blank(), axis.ticks.x = element_blank())

fig_4_B <-
  cowplot::plot_grid(
    ps[[1]] + x_blank + ggtitle('B.'),
    ps[[2]] + x_blank, 
    ps[[3]],
    ncol = 1,
    align = 'v',
    rel_heights = c(4,4,5)
  )

map_df(ps, 'data') %>% 
  # compress by storing counts rather than thousands of BAF=0 observations
  count(sample, set, state, exp_baf, baf, name='Freq') %>% 
  separate(sample, c('Accession', 'Strain_1', 'Strain_2'), sep = '\n') %>% 
  separate(set, c('Tool', 'Group'), sep = '\n') %>% 
  rename(`Expected BAF` = exp_baf, `Observed BAF` = baf, Genotype = state) %>% 
  saveRDS('11_data/fig_4B_data.rds')

fig_4_B
```

```{r fig.height=7, fig.width=8}

thm <- 
  theme(
    text = element_text(size = 8, family = 'sans'),
    plot.margin = margin(t=4, b=0, r=3, l=2),
    plot.title = element_text(margin = margin(t=0, b=0, r=0, l=0), face = 'bold')
  )

fig_4 <-
  cowplot::plot_grid(
  fig_4_A + ggtitle('A.') + thm,
  ps[[1]] + x_blank + thm + ggtitle('B.'),
  ps[[2]] + x_blank + thm, 
  ps[[3]] + thm,
  ncol = 1,
  rel_heights = c(8, 6.25, 5.8, 7),
  align = 'v',
  axis = 'l'
)


ggsave(
  filename = '11_data/figure_4.pdf', 
  plot = fig_4, 
  width = 16, 
  height = 14, 
  units = 'cm'
)
```

