---
title: "Fig S1"
output: 'github_document'
---


```{r setup}
library(tidyverse)

table_1 <- readRDS('table_1.rds')
method_order <- table_1 %>% pull(method) %>% discard(str_detect, '\\(')
method_mae_label <- table_1 %>% select(method, MAE = MAE_is_duo) %>% 
  mutate(MAE = str_extract(MAE, '[0-9\\.]+') %>% as.numeric()) %>% 
  filter(method %in% method_order) %>% 
  mutate(label = as_factor(str_c(method, '\nMAE=', format(MAE))))
bimix_tbl <- readRDS('05/bimix_tbl.rds')

is_duo_by_depth <- readRDS('05/is_duo_by_depth.rds')
is_duo_by_mp <- readRDS('05/is_duo_by_mp.rds')
is_duo_by_dist <- readRDS('05/is_duo_by_dist.rds')

is_trio_accuracy <- readRDS('05/is_trio_accuracy.rds')
```


```{r fig_s1,  fig.height=5.5, fig.width=8}
measures <- c(`F1-score`='f1_score', 
              Precision='precision', 
              `Sensitivity (recall)`='recall', 
              Specificity = 'specificity')

bind_rows(
  is_duo_by_depth %>% 
    filter(measure %in% measures) %>% 
    mutate(x_name = 'Coverage') %>% 
    rename(x_value = depth,
           y_value = value,
           y_name = measure),
  is_duo_by_mp %>% 
    filter(measure %in% measures) %>% 
    mutate(x_name = 'Minor Percent') %>% 
    rename(x_value = minor_percent,
           y_value = value,
           y_name = measure),
  is_duo_by_dist %>% 
    filter(measure %in% measures) %>% 
    mutate(x_name = 'Distance Bin') %>% 
    rename(x_value = dist_bin,
           y_value = value,
           y_name = measure)) %>% 
  filter(method %in% method_order) %>%
  mutate(
    method = factor(method, method_order),
    y_name = setNames(names(measures), measures)[y_name],
    y_name = factor(y_name, names(measures)),
    x_name = factor(x_name, c('Coverage', 'Minor Percent', 'Distance Bin')),
  ) %>% 
  rename(Tool = method) %>% 
  ggplot(aes(
    x = x_value, 
    y = y_value,
    colour = Tool,
    shape = Tool)) +
  geom_line(alpha = 1) +
  geom_point() +
  facet_grid(
    rows = vars(y_name), cols = vars(x_name),
    scales = 'free',
    switch = 'both') +
  theme(axis.title = element_blank()) +
  ggh4x::facetted_pos_scales(
    x = list(NULL,
             scale_x_continuous(trans = 'log2',
                                breaks = c(1, 2.5, 5, 10, 25, 50),
                                minor_breaks = NULL), 
             NULL))
```
